In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3139, 4348, 7136, 8068],
 [3139, 4348, 7136, 818],
 [3139, 1137, 7136, 2413],
 [9059, 2961, 9962, 1622, 1058],
 [9059, 2961, 9962, 1622, 4043],
 [2677, 3139, 3587, 7136, 9872],
 [7625, 3387, 1696, 1622]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3139 4348 7136 8068]
 [   0    0    0    0 3139 4348 7136  818]
 [   0    0    0    0 3139 1137 7136 2413]
 [   0    0    0 9059 2961 9962 1622 1058]
 [   0    0    0 9059 2961 9962 1622 4043]
 [   0    0    0 2677 3139 3587 7136 9872]
 [   0    0    0    0 7625 3387 1696 1622]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Karthick Selvam\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 257ms/step


array([[[-0.0262342 ,  0.00932367, -0.04574141, -0.00329347,
          0.00961107, -0.00959484,  0.01884223,  0.04451377,
         -0.01012756, -0.0231307 ],
        [-0.0262342 ,  0.00932367, -0.04574141, -0.00329347,
          0.00961107, -0.00959484,  0.01884223,  0.04451377,
         -0.01012756, -0.0231307 ],
        [-0.0262342 ,  0.00932367, -0.04574141, -0.00329347,
          0.00961107, -0.00959484,  0.01884223,  0.04451377,
         -0.01012756, -0.0231307 ],
        [-0.0262342 ,  0.00932367, -0.04574141, -0.00329347,
          0.00961107, -0.00959484,  0.01884223,  0.04451377,
         -0.01012756, -0.0231307 ],
        [-0.00278511,  0.01923419,  0.0220116 ,  0.0305634 ,
          0.04925212, -0.02970216,  0.00501405, -0.00363321,
          0.03757453, -0.00171174],
        [-0.03607871,  0.01908078, -0.00809904,  0.0378356 ,
         -0.04730052,  0.01313955, -0.02044815,  0.02067884,
          0.04929664,  0.01711131],
        [ 0.02387563,  0.03616068,  0.03774533, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3139, 4348, 7136, 8068])